spring.application.name=gestao_financeira

# Define a URL de conexão. Usar 'mem:testdb' cria o banco em memória.
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=0503

# CONFIGURAÇÃO DO H2 CONSOLE

spring.h2.console.enabled=true
# Define o caminho para acessar o console no navegador (ex: http://localhost:8080/h2-console)
spring.h2.console.path=/h2-console
# Permite que o console seja exibido dentro de frames (necessário se usar o Spring Security)
spring.h2.console.settings.web-allow-others=false

# CONFIGURAÇÕES ADICIONAIS (JPA/HIBERNATE)
# Mostra o SQL executado no console da aplicação
spring.jpa.show-sql=true
# Formata o SQL para ficar mais legível
spring.jpa.properties.hibernate.format_sql=true
# Atualiza a estrutura do banco automaticamente com base nas suas entidades @Entity
spring.jpa.hibernate.ddl-auto=update